EVEREST-532 Support for PSMDB operator 1.15
percona/everest-operator pull request #115
Opened 2023-10-10 11:31 UTC by gen1us2k

**CHANGE DESCRIPTION**
---
**Problem:**
EVEREST-532

*Short explanation of the problem.*

**Related pull requests**

- [link]

**Cause:**
*Short explanation of the root cause of the issue if applicable.*

**Solution:**
*Short explanation of the solution we are providing with this PR.*

**CHECKLIST**
---
**Jira**
- [ ] Is the Jira ticket created and referenced properly?

**Tests**
- [ ] Is an Integration test/test case added for the new feature/change?
- [ ] Are unit tests added where appropriate?

2023-10-10 19:45 UTC, hors requested changes

2023-10-10 19:45 UTC, hors commented on controllers/databasecluster_controller.go
> -		psmdb.Spec.Mongod.Security.EncryptionKeySecret = fmt.Sprintf("%s-mongodb-encryption-key", database.Name)
We need to move it to `spec.secrets.encryptionKey` please see https://github.com/percona/percona-server-mongodb-operator/blob/main/deploy/cr.yaml#L40

2023-10-10 19:45 UTC, hors commented on controllers/databasecluster_controller.go
> -			OperationProfiling: &psmdbv1.MongodSpecOperationProfiling{
you need to recheck default configuration/values  (I do not remember defaults) for `replsets`  and change it via https://github.com/percona/percona-server-mongodb-operator/blob/main/deploy/cr.yaml#L67C6-L67C19 if needed

2023-10-11 09:18 UTC, michal-kralik approved these changes

2023-10-11 10:04 UTC, hors approved these changes

2023-10-11 10:28 UTC, merged