EVEREST-561 Make NLB as the default Loadbalancer for EKS
percona/everest-operator pull request #126
Opened 2023-10-18 14:01 UTC by gen1us2k

**CHANGE DESCRIPTION**
---
**Problem:**
EVEREST-561 

*Short explanation of the problem.*

**Related pull requests**

- [link]

**Cause:**
*Short explanation of the root cause of the issue if applicable.*

**Solution:**
*Short explanation of the solution we are providing with this PR.*

**CHECKLIST**
---
**Jira**
- [ ] Is the Jira ticket created and referenced properly?

**Tests**
- [ ] Is an Integration test/test case added for the new feature/change?
- [ ] Are unit tests added where appropriate?

2023-10-18 14:48 UTC, hors requested changes

2023-10-18 14:48 UTC, hors commented on controllers/databasecluster_controller.go
> +			"service.beta.kubernetes.io/aws-load-balancer-type":                    "external",
please remove 131 line

2023-10-19 07:58 UTC, hors approved these changes

2023-10-19 08:08 UTC, michal-kralik approved these changes

2023-10-19 09:02 UTC, gen1us2k commented on controllers/databasecluster_controller.go
> +			"service.beta.kubernetes.io/aws-load-balancer-type":                    "external",
Done

2023-10-19 09:02 UTC, merged