EVEREST-496 Playing with reconcilers
percona/everest-operator pull request #169
Opened 2023-11-16 16:41 UTC by gen1us2k

**CHANGE DESCRIPTION**
---
**Problem:**
EVEREST-0

*Short explanation of the problem.*

**Related pull requests**

- [link]

**Cause:**
*Short explanation of the root cause of the issue if applicable.*

**Solution:**
*Short explanation of the solution we are providing with this PR.*

**CHECKLIST**
---
**Jira**
- [ ] Is the Jira ticket created and referenced properly?

**Tests**
- [ ] Is an Integration test/test case added for the new feature/change?
- [ ] Are unit tests added where appropriate?

2023-11-17 08:05 UTC, gen1us2k commented on config/manager/manager.yaml
> +        - name: EVEREST_NAMESPACE
This namespace will be primary, yet during the deployment we need to set WATCH_NAMESPACES=namespace1,namespace2 to run reconciliation logic there

2023-11-17 08:05 UTC, gen1us2k commented on config/manifests/bases/everest-operator.clusterserviceversion.yaml
>    - supported: true
Yet I have no idea of how it will work with the RBAC stuff

2023-11-17 08:05 UTC, gen1us2k commented on controllers/databasecluster_controller.go
> +	everestNamespace string
Storing the value of EVEREST_NAMESPACE env var

2023-11-17 08:05 UTC, gen1us2k commented on controllers/databasecluster_controller.go
> +			if err := r.reconcileSecret(ctx, backupStorage, database); err != nil {
Create or update secret in the targetNamespace

2023-11-17 08:05 UTC, gen1us2k commented on controllers/databasecluster_controller.go
> +		return fmt.Errorf("%s namespace is not allowed to use for %s backup storage", database.Namespace, backupStorage.Name)
I assume we need to improve validation on the BE side as well

2023-11-17 08:05 UTC, gen1us2k commented on main.go
> +	if err := dbReconciler.SetupWithManager(mgr); err != nil {
Yep, I know that the controller for BackupStorage is missing to run the reconciliation loop either for backupstorage update or for a secret update

2023-11-17 09:28 UTC, oksana-grishchenko reviewed
In general the idea with `targetNamespaces` for the allowed list and `status.namespaces` for the actual list looks good, however to keep the lists consistent we would need to handle the deletion of 
- the targetNamespaces
- the actual namespaces in the cluster

2023-11-17 09:28 UTC, oksana-grishchenko commented on api/v1alpha1/backupstorage_types.go
> +	b.Status.Namespaces[namespace] = true
we only add the namespaces to the Status but not delete them, it means we may end up in the situation when a namespace is listed in the Status but not even exists in the cluster. Is it an intended trade-off?

2023-11-17 09:28 UTC, oksana-grishchenko commented on api/v1alpha1/backupstorage_types.go
> +func (b *BackupStorage) IsNamespaceAllowed(namespace string) bool {
What should happen with an existing db cluster if the SRE removes it's namespace from the targetNamespaces?

2023-11-17 09:28 UTC, oksana-grishchenko commented on api/v1alpha1/backupstorage_types.go
> +	TargetNamespaces []string `json:"targetNamespaces"`
We'll also need to validate that the listed namespaces exist

2023-11-17 12:11 UTC, recharte commented on api/v1alpha1/backupstorage_types.go
> +	Namespaces map[string]bool `json:"usedNamespaces"`
I don't think we need this, the idea would be to use the same logic we use for [creating the PMM secret](https://github.com/percona/everest-operator/blob/14c108b7a9b92c43f65fd2b800f0f31bbc029689/controllers/databasecluster_controller.go#L652-L656) or the [backup secret for PG](https://github.com/percona/everest-operator/blob/14c108b7a9b92c43f65fd2b800f0f31bbc029689/controllers/databasecluster_controller.go#L1975-L1985).

2023-11-17 14:34 UTC, gen1us2k commented on api/v1alpha1/backupstorage_types.go
> +	Namespaces map[string]bool `json:"usedNamespaces"`
We need this because I don't want to violate security best practices

2023-11-17 14:34 UTC, gen1us2k commented on api/v1alpha1/backupstorage_types.go
> +func (b *BackupStorage) IsNamespaceAllowed(namespace string) bool {
It will be deleted

2023-11-21 14:20 UTC, gen1us2k commented on controllers/databasecluster_controller.go
> -	version, err := r.getOperatorVersion(context.Background(), types.NamespacedName{
We can drop support for the 1.12 PSMDB operator

2023-11-21 17:27 UTC, oksana-grishchenko approved these changes
The implementation itself looks good, my concerns are resolved. Approving the PR to unblock it in case the massive "Cons" section is considered by the product as the limitations we can live with.

2023-11-21 17:27 UTC, oksana-grishchenko commented on api/v1alpha1/backupstorage_types.go
> +func (b *BackupStorage) IsNamespaceAllowed(namespace string) bool {
acceptable

2023-11-21 20:06 UTC, recharte reviewed
Overall the PR looks like it is functionally correct however, I think the followed approach is overly complex.

I argue that we don't need the BackupStorage controller at all. We already have an [index](https://github.com/percona/everest-operator/blob/fdaa0adc929a918419f14418fa36709771bb85c6/controllers/databasecluster_controller.go#L2677-L2695) and [watcher](https://github.com/percona/everest-operator/blob/fdaa0adc929a918419f14418fa36709771bb85c6/controllers/databasecluster_controller.go#L2780-L2785) configured in the DBC controller that runs the reconciliation loop every time a secret referenced by a BS triggers an event.
Therefore, we can use this same mechanism to create or update the end secret without needing to keep track of any namespace. In a sense we can think of this secret as being linked to a specific DBC than to the generic BS.

Moreover, we already use this approach for PG because the secret format needs to be different than the one specified in the BS which is the same for PXC/PSMDB. See [here](https://github.com/percona/everest-operator/blob/fdaa0adc929a918419f14418fa36709771bb85c6/controllers/databasecluster_controller.go#L1995-L2005) and [here](https://github.com/percona/everest-operator/blob/fdaa0adc929a918419f14418fa36709771bb85c6/controllers/databasecluster_controller.go#L1336-L1369)

2023-11-22 16:13 UTC, gen1us2k commented
> I argue that we don't need the BackupStorage controller at all. We already have an [index](https://github.com/percona/everest-operator/blob/fdaa0adc929a918419f14418fa36709771bb85c6/controllers/databasecluster_controller.go#L2677-L2695) and [watcher](https://github.com/percona/everest-operator/blob/fdaa0adc929a918419f14418fa36709771bb85c6/controllers/databasecluster_controller.go#L2780-L2785) configured in the DBC controller that runs the reconciliation loop every time a secret referenced by a BS triggers an event.
Therefore, we can use this same mechanism to create or update the end secret without needing to keep track of any namespace. In a sense we can think of this secret as being linked to a specific DBC than to the generic BS.


> Moreover, we already use this approach for PG because the secret format needs to be different than the one specified in the BS which is the same for PXC/PSMDB. See [here](https://github.com/percona/everest-operator/blob/fdaa0adc929a918419f14418fa36709771bb85c6/controllers/databasecluster_controller.go#L1995-L2005) and [here](https://github.com/percona/everest-operator/blob/fdaa0adc929a918419f14418fa36709771bb85c6/controllers/databasecluster_controller.go#L1336-L1369)


Well, this was my first approach to solving the issue. This works fine for the backupStorages or monitoringConfigs in the single namespace scenario. 

Since the idea is to create backupstorages or monitoring configs in the default namespace (percona-everest) the existence of the objects is only in the default namespace. However, databasecluster controller replicates secrets across namespaces (since they are namespaced) there's no way (at least I know) to bind that secret with the backupStorage or monitoringConfig. Since the logic for backup storage and monitoring config is the same I'll describe the flow based on backup storage

Let's take a look at the backup storage In the default namespace. To ensure that the secret will be deleted we can use ownerreferences here and we don't quite need a controller here. The backend or some other controller can create it for you yet, once the backupstorage is deleted, the secret will be deleted as well.

Since secrets are namespaced to enable the multi namespace support in the cluster-wide mode we need to replicate them to the targetNamespace during the reconciliation of database clusters(because this is the only place when we need to ensure that the secret exists). We can't use ownerreferences here because they are not designed for that and we need to come up with a way to store the information where the secret was created. Here are the labels to link the secret in the different namespace with the existing backup storage. 

After testing this using indexers and watchers, when the user tries to delete the secret from a different namespace the reconciliation loop does not start because there's no event generated/passed to the operator after the deletion and it ends in the inconsistent state.

Hence, we need to have an additional controller to ensure that after backup storage deletion, all secrets across all namespaces will be created and here we have finalizers as an additional handle to block the deletion. We need to delete all secrets across all namespaces except the default one (because we use owner references here and the deletion might block here because of cross-linking between entities)

Since the backupstorage controller is namespaced (because we create backup storages only in the default namespace) we need to have a way to watch for secrets and run reconciliation of the backup storage entity on the secret change. For the default secret in the default namespace we have `Owns` for that and this works fine. For all other namespaces, we need to listen to secrets and run a reconcile loop only for labeled secrets.

I hope that it explains the solution after a couple of days of trying to implement as simply as I can.

2023-11-23 09:47 UTC, recharte requested changes
This is such an important change that we can't merge it without proper tests for it.

2023-11-23 10:27 UTC, recharte reviewed
While reviewing I found a couple of tiny code style improvements, these are just some nitpicks so feel free to ignore them.

2023-11-23 10:27 UTC, recharte commented on controllers/databasecluster_controller.go
> +	}
```suggestion
	if err != nil && !k8serrors.IsNotFound(err) {
		return err
	}
```

2023-11-23 10:27 UTC, recharte commented on controllers/databasecluster_controller.go
> +	return nil
```suggestion
	return r.Create(ctx, secret)
```

2023-11-23 10:27 UTC, recharte commented on controllers/databasecluster_controller.go
> +	}
```suggestion
	if err != nil && !k8serrors.IsNotFound(err) {
		return err
	}
```

2023-11-23 10:27 UTC, recharte commented on controllers/databasecluster_controller.go
> +	return nil
```suggestion
	return r.Create(ctx, secret)
```

2023-11-23 10:37 UTC, recharte commented on api/v1alpha1/backupstorage_types.go
> +	TargetNamespaces []string `json:"targetNamespaces,omitempty"`
This needs to be discussed with Peter and Nuna, giving the user this responsibility wasn't part of the product requirements.

2023-11-23 12:06 UTC, recharte commented on api/v1alpha1/backupstorage_types.go
> +	TargetNamespaces []string `json:"targetNamespaces,omitempty"`
Agreed on this approach.

2023-11-23 14:54 UTC, recharte approved these changes
Thank you for adding the tests :hugs:.
I think that the only important case we're missing would be to validate the TargetNamespaces feature works as intended but that's part of the error cases which we aren't testing anywhere so I can't say this is mandatory for now.

2023-11-23 14:54 UTC, recharte commented on e2e-tests/tests/features/multinamespace_pg/10-assert.yaml
> +---
```suggestion
```

2023-11-23 16:02 UTC, merged