EVEREST-356 Fixed restart logic for all clusters
percona/everest-operator pull request #71
Opened 2023-09-11 13:19 UTC by gen1us2k

2023-09-11 14:20 UTC, gen1us2k commented on controllers/databasecluster_controller.go
> +	return reconcile.Result{}, nil
It was a leftover from the first POC. We discussed it with Ege and I left it intentionally to test this feature. Looks like we do not need it because we watch for the resources

2023-09-11 14:20 UTC, gen1us2k commented on controllers/databasecluster_controller.go
> +		if err := r.Update(ctx, database); err != nil {
We need to persist the changed field in etcd

2023-09-11 15:50 UTC, recharte requested changes

2023-09-11 15:50 UTC, recharte commented on Makefile
> +	KUBECONFIG=~/.kube/test-minikube kubectl kuttl test --config ./e2e-tests/kuttl-eks-features.yml --test monitoringconfig_pg
I don't think you meant to commit these...

2023-09-12 07:14 UTC, oksana-grishchenko approved these changes

2023-09-12 10:25 UTC, recharte approved these changes

2023-09-12 10:27 UTC, merged